version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: reimbursement-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reimbursement
    ports:
      - "5433:5432"
